language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-25
    - extra-google-google_play_services
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
     - chmod +x gradlew
script:
    - ./gradlew build -x lint